version: "3"
services:
  web:
    environment:
      - DB_URL=mongodb://maitredb_db_1
      - API_PORT=3000
    build: .
    image: tfpractice/maitredb
    networks:
      - frontend
      - backend
    volumes:
     - .:/app
    ports:
      - 3000:3000
  db:
    image: 'mongo'
    volumes:
     - db-data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
      
networks:
  frontend:
  backend:

volumes:
  db-data:
